version: '2'
services:
  postgres:
    container_name: ethereum_postgres
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=ethereum
      - POSTGRES_PASSWORD=ethereum
